version: "3"
networks:
  default:
    external:
      name: "localdev"
services:
  api:
    container_name: collector-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/APP
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: collector-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: collector
